### ISSUE TITLE
[bug]Error occurred while enabling ctLib v0.0.3 (Is it up to date?)

### ISSUE THREAD

**Issue by xiaole29999** [CSneko/ctLib#1]
复现环境：Java 19 (Java HotSpot(TM) 64-Bit Server VM 19.0.2+7-44) Host: Linux 6.1.0-11-amd64 (amd64)
服务器核心：purpur-1.20.1-2062.jar
复现操作：安装插件，启动服务器即可复现
插件版本：ctLib0.0.3
具体描述：
Error occurred while enabling ctLib v0.0.3 (Is it up to date?) java.lang.NullPointerException:Cannot invoke "java.sql.Connection.getMetaData()"because"com.crystalneko.ctlib.sql.mysql.mysqlconnection" is null

**Comment by CSneko** [comment]
这貌似是由于没有设置mysql服务器导致的，在新版本已经修复
