### ISSUE TITLE
ctLib无法与floodgate兼容（全版本无法兼容，包括bukkit及其下游服务端,fabric服务端）

### ISSUE THREAD

**Issue by xiaole2999** [CSneko/ctLib#2]
复现环境：Java 19 (Java HotSpot(TM) 64-Bit Server VM 19.0.2+7-44) Host: Linux 6.1.0-11-amd64 (amd64)
服务器核心：**所有核心**均可复现（实例为**fabric**）
复现操作：安装ctlib,geyser-fabric,floodgate-fabric，启动服务器即可复现
插件版本：floodgate-fabric-2.2.0,ctLibMod-0.0.11,geyser-fabric#402Build
具体描述：
[2023-12-16-6.log](https://github.com/CSneko/ctLib/files/13691459/2023-12-16-6.log)

**Comment by CSneko** [comment]
出于一些原因，这个问题可能无法得到很好的解决，目前唯一的解决办法是以压缩包形式打开mod的jar文件，并删除`config.yml`
![图片](https://github.com/CSneko/ctLib/assets/135438028/221b7c76-592d-4c71-886b-c4f6032dd29e)
不过请注意，删除config.yml在Fabric/Forge端无影响，但是在Bukkit/Velocity会受到一定影响，如果在Bukkit/Velocity端需要同时运行Floodgate，请手动将`config.yml`复制到`plugins/ctLib/config.yml`

**Comment by xiaole2999** [comment]
> 出于一些原因，这个问题可能无法得到很好的解决，目前唯一的解决办法是以压缩包形式打开mod的jar文件，并删除`config.yml` ![图片](https://private-user-images.githubusercontent.com/135438028/290977339-221b7c76-592d-4c71-886b-c4f6032dd29e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MTA1NzYsIm5iZiI6MTcwMjcxMDI3NiwicGF0aCI6Ii8xMzU0MzgwMjgvMjkwOTc3MzM5LTIyMWI3Yzc2LTU5MmQtNGM3MS04ODZiLWM0ZjYwMzJkZDI5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNlQwNzA0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZmU4MThjOGUzMDlmYzQ5NzQ3OTkzYWVjY2NiNDQ2NjkwZmU3OTNkMzQyOWRlZWViMTBhMzdiOTA1NzVkNjhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fYUQoWeHmJZCtC0pAlhS8zGc-99smuvk23CF-2YtJpA) 不过请注意，删除config.yml在Fabric/Forge端无影响，但是在Bukkit/Velocity会受到一定影响，如果在Bukkit/Velocity端需要同时运行Floodgate，请手动将`config.yml`复制到`plugins/ctLib/config.yml`

ok,我试试
————————
可以启动了
