### ISSUE TITLE
[Suggest] Lib库下载出现错误

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [CSneko/ctLib#4]
我认为这可能是因为我服务器本地网络引发的问题，但的确这个问题还是比较困扰我的
我尝试过使用clash来解决此问题，但很显然失败了，我们是否可以换一个访问速度更快的Lib源呢
Logs: https://paste.ubuntu.com/p/cQHYgntw3b/

**Comment by CSneko** [comment]
由于插件受众范围较广，因此选择中心maven库是最佳选择，这里有一种可能的解决方案：使用Mod版本的ctlib,因为mod版本的ctlib和插件版本最大的不同就是mod版本自带了一些重要的lib

**Comment by xiaoyueyoqwq** [comment]
> 由于插件受众范围较广，因此选择中心maven库是最佳选择，这里有一种可能的解决方案：使用Mod版本的ctlib,因为mod版本的ctlib和插件版本最大的不同就是mod版本自带了一些重要的lib

或者我们可不可以尝试一下将需要从互联网下载的lib库单独打包到一个版本的插件内，概念有点类似于paper上游核心构建的两个版本：paperclip和bundler，其中bundler版本就自带完整的lib库

**Comment by CSneko** [comment]
其实这并不容易，ctlib允许**任何插件**在**任何时间**调用下载，因此这样只能治标不治本，如果可以，后面我会考虑添加更多的源来解决这个问题

**Comment by xiaoyueyoqwq** [comment]
> 其实这并不容易，ctlib允许**任何插件**在**任何时间**调用下载，因此这样只能治标不治本，如果可以，后面我会考虑添加更多的源来解决这个问题

了解，感谢您的回复
